apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.registry }}:{{ .Values.version }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.02"
              memory: 50Mi
          ports:
            - name: http-web
              containerPort: 8000
          env:
            - name: KEYS_VERSION
              value: {{ .Values.version | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.dopplerSecretName }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.configFile.mountPath }}
              subPath: {{ .Values.configFile.name }}
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
      {{- if .Values.registrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.registrySecretName }}
      {{- end }}
